coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 0%
      backend:
        target: 80%
        threshold: 0%
        flags:
          - backend
      frontend:
        target: 80%
        threshold: 0%
        flags:
          - frontend
    patch:
      default:
        target: 80%
        threshold: 0%

flags:
  backend:
    paths:
      - core/
  frontend:
    paths:
      - client/src/
