# Generated by Django 5.1.1 on 2024-10-05 09:16
# Modified: removed AUTH_USER_MODEL dependency (auth app removed, FK dropped in 0006)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('source', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mots_cles', models.ManyToManyField(to='factcheck.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('vérifié', 'Vérifié'), ('rejeté', 'Rejeté')], default='en cours', max_length=50)),
                ('utilisateur', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('vidéo', 'Vidéo')], max_length=50)),
                ('fichier', models.FileField(upload_to='verified_media/')),
                ('description', models.TextField(blank=True, null=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factcheck.fact')),
            ],
        ),
    ]
