# Generated by Django 5.1.1 on 2024-10-05 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
