# Generated by Django 5.1.1 on 2024-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0002_keyword_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='web_sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
