# Generated by Django 5.1.1 on 2024-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0004_submission_detailed_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='web_sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
