# Generated by Django 5.1.1 on 2026-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0009_alter_imageverification_model_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('vérifié', 'Vérifié'), ('rejeté', 'Rejeté'), ('indéterminé', 'Indéterminé'), ('erreur', 'Erreur')], default='en cours', max_length=50),
        ),
    ]
